name: Android CI

on:
  push:
    branches: [ "new" ]
  pull_request:
    branches: [ "new" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 8512546

    - name: Fetch 3rd library
      run: |
        cd 3rd
        chmod +x ./download_3rd_lib.sh && ./download_3rd_lib.sh
        wget https://github.com/ningshanwutuobang/Kirikiroid2/releases/download/new_runnable/prebuilt.zip
        unzip -fo prebuilt.zip
        cd ..
        wget https://github.com/ningshanwutuobang/Kirikiroid2/releases/download/new_runnable/Resources.zip
        unzip -fo Resources.zip

    - name: Build with Gradle
      run: |
        chmod +x proj.andorid/gradlew
        cd proj.android && ./gradlew build
